services:
  #Database mySQL
  mysql:
    image: mysql:8.0
    container_name: doit-mysql
    restart: always
    env_file:
      - ./.env.docker
    ports:
      - '3307:3306'
    volumes:
      - mysql_data:/var/lib/mysql

  # Backend 
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    container_name: doit-backend
    restart: always
    env_file:
      - ./backend/.env.backend
    ports:
      - '3000:3000'
    volumes:
      - /var/log/doit:/app/logs
    depends_on:
      - mysql

  # Monitor
  log-monitor:
    build:
      context: ./monitor
      dockerfile: Dockerfile.monitor
    container_name: doit-monitor
    restart: always
    env_file:
      - ./monitor/.env.monitor
    volumes:
      - /var/log/doit:/app/backend/logs:ro
    depends_on:
        - backend

# Frontend build 
  frontend_builder:
    build:
      context: .
      dockerfile: frontend/Dockerfile.build 
    container_name: doit-frontend-builder
    volumes:
      - frontend_build:/usr/share/app/frontend

# Nginx
  nginx: 
    image: nginx:alpine
    container_name: doit-nginx
    network_mode: host
    restart: always
    volumes:
      # Config
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - frontend_build:/usr/share/nginx/html:ro
      - /var/log/nginx:/var/log/nginx
    depends_on:
      - backend 
      - frontend_builder 
volumes:
  mysql_data:
  frontend_build:
      