services:
  #Database mySQL
  mysql:
    image: mysql:8.0
    container_name: doit-mysql
    restart: always
    env_file:
      - ./.env.docker
    ports:
      - '3307:3306'
    volumes:
      - mysql_data:/var/lib/mysql

# Backend 
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: doit-backend
    restart: always
    env_file:
      - ./backend/.env.backend
    ports:
      - '3000:3000'
    depends_on:
      - mysql

volumes:
  mysql_data:
      